NIFTY50_COMPANIES: dict[str, str] = {
    "ADANIENT":   "Adani Enterprises",
    "ADANIPORTS":  "Adani Ports",
    "APOLLOHOSP":  "Apollo Hospitals",
    "ASIANPAINT":  "Asian Paints",
    "AXISBANK":    "Axis Bank",
    "BAJAJ-AUTO":  "Bajaj Auto",
    "BAJFINANCE":  "Bajaj Finance",
    "BAJAJFINSV":  "Bajaj Finserv",
    "BEL":         "Bharat Electronics",
    "BPCL":        "Bharat Petroleum",
    "BHARTIARTL":  "Bharti Airtel",
    "BRITANNIA":   "Britannia Industries",
    "CIPLA":       "Cipla",
    "COALINDIA":   "Coal India",
    "DRREDDY":     "Dr Reddys Laboratories",
    "EICHERMOT":   "Eicher Motors",
    "ETERNAL":     "Eternal Zomato",
    "GRASIM":      "Grasim Industries",
    "HCLTECH":     "HCL Technologies",
    "HDFCBANK":    "HDFC Bank",
    "HDFCLIFE":    "HDFC Life Insurance",
    "HEROMOTOCO":  "Hero MotoCorp",
    "HINDALCO":    "Hindalco Industries",
    "HINDUNILVR":  "Hindustan Unilever",
    "ICICIBANK":   "ICICI Bank",
    "INDUSINDBK":  "IndusInd Bank",
    "INFY":        "Infosys",
    "ITC":         "ITC",
    "JSWSTEEL":    "JSW Steel",
    "KOTAKBANK":   "Kotak Mahindra Bank",
    "LT":          "Larsen Toubro",
    "M&M":         "Mahindra Mahindra",
    "MARUTI":      "Maruti Suzuki",
    "NESTLEIND":   "Nestle India",
    "NTPC":        "NTPC",
    "ONGC":        "ONGC",
    "POWERGRID":   "Power Grid Corporation",
    "RELIANCE":    "Reliance Industries",
    "SBIN":        "State Bank of India",
    "SHRIRAMFIN":  "Shriram Finance",
    "SUNPHARMA":   "Sun Pharmaceutical",
    "TCS":         "Tata Consultancy Services",
    "TATACONSUM":  "Tata Consumer Products",
    "TATAMOTORS":  "Tata Motors",
    "TATASTEEL":   "Tata Steel",
    "TECHM":       "Tech Mahindra",
    "TITAN":       "Titan Company",
    "TRENT":       "Trent",
    "ULTRACEMCO":  "UltraTech Cement",
    "WIPRO":       "Wipro",
}

NIFTY50_SYMBOLS: list[str] = list(NIFTY50_COMPANIES.keys())
