# NSE 500 (Nifty 500) stock list — top 500 companies by float-adjusted market cap.
#
# This file ships with ~200 high-confidence stocks (Nifty 50 + Nifty Next 50 +
# prominent midcaps). Run scripts/fetch_nse500.py to regenerate with the full
# accurate 500-stock constituent list directly from NSE archives.
#
# Refresh: python3 scripts/fetch_nse500.py

NSE500_COMPANIES: dict[str, str] = {
    # ── Nifty 50 ──────────────────────────────────────────────────────────────
    "ADANIENT":   "Adani Enterprises",
    "ADANIPORTS":  "Adani Ports",
    "APOLLOHOSP":  "Apollo Hospitals",
    "ASIANPAINT":  "Asian Paints",
    "AXISBANK":    "Axis Bank",
    "BAJAJ-AUTO":  "Bajaj Auto",
    "BAJFINANCE":  "Bajaj Finance",
    "BAJAJFINSV":  "Bajaj Finserv",
    "BEL":         "Bharat Electronics",
    "BPCL":        "Bharat Petroleum",
    "BHARTIARTL":  "Bharti Airtel",
    "BRITANNIA":   "Britannia Industries",
    "CIPLA":       "Cipla",
    "COALINDIA":   "Coal India",
    "DRREDDY":     "Dr Reddys Laboratories",
    "EICHERMOT":   "Eicher Motors",
    "ETERNAL":     "Eternal Zomato",
    "GRASIM":      "Grasim Industries",
    "HCLTECH":     "HCL Technologies",
    "HDFCBANK":    "HDFC Bank",
    "HDFCLIFE":    "HDFC Life Insurance",
    "HEROMOTOCO":  "Hero MotoCorp",
    "HINDALCO":    "Hindalco Industries",
    "HINDUNILVR":  "Hindustan Unilever",
    "ICICIBANK":   "ICICI Bank",
    "INDUSINDBK":  "IndusInd Bank",
    "INFY":        "Infosys",
    "ITC":         "ITC",
    "JSWSTEEL":    "JSW Steel",
    "KOTAKBANK":   "Kotak Mahindra Bank",
    "LT":          "Larsen and Toubro",
    "M&M":         "Mahindra and Mahindra",
    "MARUTI":      "Maruti Suzuki",
    "NESTLEIND":   "Nestle India",
    "NTPC":        "NTPC",
    "ONGC":        "ONGC",
    "POWERGRID":   "Power Grid Corporation",
    "RELIANCE":    "Reliance Industries",
    "SBIN":        "State Bank of India",
    "SHRIRAMFIN":  "Shriram Finance",
    "SUNPHARMA":   "Sun Pharmaceutical",
    "TCS":         "Tata Consultancy Services",
    "TATACONSUM":  "Tata Consumer Products",
    "TATAMOTORS":  "Tata Motors",
    "TATASTEEL":   "Tata Steel",
    "TECHM":       "Tech Mahindra",
    "TITAN":       "Titan Company",
    "TRENT":       "Trent",
    "ULTRACEMCO":  "UltraTech Cement",
    "WIPRO":       "Wipro",

    # ── Nifty Next 50 ─────────────────────────────────────────────────────────
    "ADANIGREEN":  "Adani Green Energy",
    "ADANIPOWER":  "Adani Power",
    "AMBUJACEM":   "Ambuja Cements",
    "ATGL":        "Adani Total Gas",
    "BAJAJHLDNG":  "Bajaj Holdings and Investment",
    "BANKBARODA":  "Bank of Baroda",
    "BERGEPAINT":  "Berger Paints India",
    "BOSCHLTD":    "Bosch",
    "CANBK":       "Canara Bank",
    "CHOLAFIN":    "Cholamandalam Investment and Finance",
    "COLPAL":      "Colgate Palmolive India",
    "DABUR":       "Dabur India",
    "DLF":         "DLF",
    "DIVISLAB":    "Divis Laboratories",
    "GAIL":        "GAIL India",
    "GODREJCP":    "Godrej Consumer Products",
    "GODREJPROP":  "Godrej Properties",
    "HAL":         "Hindustan Aeronautics",
    "HAVELLS":     "Havells India",
    "ICICIGI":     "ICICI Lombard General Insurance",
    "ICICIPRULI":  "ICICI Prudential Life Insurance",
    "INDIGO":      "InterGlobe Aviation",
    "IOC":         "Indian Oil Corporation",
    "IGL":         "Indraprastha Gas",
    "JIOFIN":      "Jio Financial Services",
    "LICI":        "Life Insurance Corporation of India",
    "LUPIN":       "Lupin",
    "MARICO":      "Marico",
    "MOTHERSON":   "Samvardhana Motherson International",
    "MUTHOOTFIN":  "Muthoot Finance",
    "NHPC":        "NHPC",
    "PFC":         "Power Finance Corporation",
    "PIDILITIND":  "Pidilite Industries",
    "PNB":         "Punjab National Bank",
    "RECLTD":      "REC Limited",
    "SAIL":        "Steel Authority of India",
    "SIEMENS":     "Siemens India",
    "SRF":         "SRF",
    "TORNTPHARM":  "Torrent Pharmaceuticals",
    "TVSMOTOR":    "TVS Motor Company",
    "UNIONBANK":   "Union Bank of India",
    "UPL":         "UPL",
    "VBL":         "Varun Beverages",
    "VEDL":        "Vedanta",
    "ZYDUSLIFE":   "Zydus Lifesciences",

    # ── Nifty Midcap 150 (prominent constituents) ─────────────────────────────
    "ABCAPITAL":   "Aditya Birla Capital",
    "ALKEM":       "Alkem Laboratories",
    "ASHOKLEY":    "Ashok Leyland",
    "ASTRAL":      "Astral",
    "AUROPHARMA":  "Aurobindo Pharma",
    "BALKRISIND":  "Balkrishna Industries",
    "BATAINDIA":   "Bata India",
    "BIOCON":      "Biocon",
    "BLUESTARCO":  "Blue Star",
    "CANFINHOME":  "Can Fin Homes",
    "CDSL":        "Central Depository Services India",
    "CESC":        "CESC",
    "COFORGE":     "Coforge",
    "CONCOR":      "Container Corporation of India",
    "CROMPTON":    "Crompton Greaves Consumer Electricals",
    "CUMMINSIND":  "Cummins India",
    "DEEPAKNTR":   "Deepak Nitrite",
    "DIXON":       "Dixon Technologies India",
    "ESCORTS":     "Escorts Kubota",
    "EXIDEIND":    "Exide Industries",
    "FEDERALBNK":  "Federal Bank",
    "FORTIS":      "Fortis Healthcare",
    "GLENMARK":    "Glenmark Pharmaceuticals",
    "GNFC":        "Gujarat Narmada Valley Fertilizers and Chemicals",
    "GODREJIND":   "Godrej Industries",
    "HFCL":        "HFCL",
    "IDFCFIRSTB":  "IDFC First Bank",
    "INDHOTEL":    "Indian Hotels Company",
    "INDUSTOWER":  "Indus Towers",
    "IRCTC":       "Indian Railway Catering and Tourism Corporation",
    "JKCEMENT":    "JK Cement",
    "JSWENERGY":   "JSW Energy",
    "JSWINFRA":    "JSW Infrastructure",
    "JUBLFOOD":    "Jubilant FoodWorks",
    "KALYANKJIL":  "Kalyan Jewellers India",
    "KANSAINER":   "Kansai Nerolac Paints",
    "KPITTECH":    "KPIT Technologies",
    "LICHSGFIN":   "LIC Housing Finance",
    "LINDEINDIA":  "Linde India",
    "LTTS":        "L&T Technology Services",
    "M&MFIN":      "Mahindra and Mahindra Financial Services",
    "MAXHEALTH":   "Max Healthcare Institute",
    "METROPOLIS":  "Metropolis Healthcare",
    "MGL":         "Mahanagar Gas",
    "MPHASIS":     "Mphasis",
    "NAUKRI":      "Info Edge India",
    "NAVINFLUOR":  "Navin Fluorine International",
    "NLCINDIA":    "NLC India",
    "OBEROIRLTY":  "Oberoi Realty",
    "OFSS":        "Oracle Financial Services Software",
    "PAGEIND":     "Page Industries",
    "PHOENIXLTD":  "Phoenix Mills",
    "PIIND":       "PI Industries",
    "POLYCAB":     "Polycab India",
    "PRESTIGE":    "Prestige Estates Projects",
    "RAYMOND":     "Raymond",
    "SJVN":        "SJVN",
    "SONACOMS":    "Sona BLW Precision Forgings",
    "SUMICHEM":    "Sumitomo Chemical India",
    "SUNDRMFAST":  "Sundram Fasteners",
    "SUNGENE":     "Syngene International",
    "SUNTV":       "Sun TV Network",
    "TATACHEM":    "Tata Chemicals",
    "TATACOMM":    "Tata Communications",
    "TATAPOWER":   "Tata Power Company",
    "THERMAX":     "Thermax",
    "TORNTPOWER":  "Torrent Power",
    "UNOMINDA":    "Uno Minda",
    "VGUARD":      "V-Guard Industries",
    "VOLTAS":      "Voltas",
    "ZEEL":        "Zee Entertainment Enterprises",

    # ── Other prominent NSE 500 companies ─────────────────────────────────────
    "AAVAS":       "Aavas Financiers",
    "ABFRL":       "Aditya Birla Fashion and Retail",
    "AIAENG":      "AIA Engineering",
    "ANGELONE":    "Angel One",
    "ATUL":        "Atul",
    "AUBANK":      "AU Small Finance Bank",
    "BSE":         "BSE",
    "CGPOWER":     "CG Power and Industrial Solutions",
    "CHOLAHLDNG":  "Cholamandalam Financial Holdings",
    "DALBHARAT":   "Dalmia Bharat",
    "DMART":       "Avenue Supermarts",
    "EMAMILTD":    "Emami",
    "EPLLTD":      "EPL",
    "FLUOROCHEM":  "Gujarat Fluorochemicals",
    "GRINDWELL":   "Grindwell Norton",
    "GSPL":        "Gujarat State Petronet",
    "HGINFRA":     "H.G. Infra Engineering",
    "HINDCOPPER":  "Hindustan Copper",
    "IDBI":        "IDBI Bank",
    "ICICISEC":    "ICICI Securities",
    "INOXWIND":    "Inox Wind",
    "JKPAPER":     "JK Paper",
    "KEI":         "KEI Industries",
    "KFINTECH":    "KFin Technologies",
    "LATENTVIEW":  "Latent View Analytics",
    "LALPATHLAB":  "Dr Lal PathLabs",
    "LICI":        "Life Insurance Corporation of India",
    "MANKIND":     "Mankind Pharma",
    "MAPMYINDIA":  "C.E. Info Systems",
    "NATCOPHARM":  "Natco Pharma",
    "NIACL":       "New India Assurance Company",
    "PERSISTENT":  "Persistent Systems",
    "PGHH":        "Procter and Gamble Hygiene and Health Care",
    "PNBHOUSING":  "PNB Housing Finance",
    "PRICOLLTD":   "Pricol",
    "RBLBANK":     "RBL Bank",
    "RITES":       "RITES",
    "ROUTE":       "Route Mobile",
    "SBILIFE":     "SBI Life Insurance Company",
    "SBICARD":     "SBI Cards and Payment Services",
    "STARHEALTH":  "Star Health and Allied Insurance",
    "SYNGENE":     "Syngene International",
    "TATAELXSI":   "Tata Elxsi",
    "TIINDIA":     "Tube Investments of India",
    "TIMKEN":      "Timken India",
    "TTKPRESTIG":  "TTK Prestige",
    "TVSHLTD":     "TVS Holdings",
    "UTIAMC":      "UTI Asset Management Company",
    "VIPIND":      "VIP Industries",
    "WHIRLPOOL":   "Whirlpool of India",
}

NSE500_SYMBOLS: list[str] = list(NSE500_COMPANIES.keys())
